apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
binaryData:
  init.sql: Ci8qQ1JFQVRFIFVTRVIgJ2F1dGhfdXNlcidAJyUnIElERU5USUZJRUQgQlkgJ0F1dGgxMjMnOwpHUkFOVCBBTEwgUFJJVklMRUdFUyBPTiBhdXRoLiogVE8gJ2F1dGhfdXNlcidAJyUnOwoKRkxVU0ggUFJJVklMRUdFUzsqLwoKVVNFIGF1dGg7CgpDUkVBVEUgVEFCTEUgdXNlciAoCiAgaWQgSU5UIE5PVCBOVUxMIEFVVE9fSU5DUkVNRU5UIFBSSU1BUlkgS0VZLAogIGVtYWlsIFZBUkNIQVIoMjU1KSBOT1QgTlVMTCBVTklRVUUsCiAgcGFzc3dvcmQgVkFSQ0hBUigyNTUpIE5PVCBOVUxMCik7CgpJTlNFUlQgSU5UTyB1c2VyIChlbWFpbCwgcGFzc3dvcmQpIFZBTFVFUyAoJ3BhdWxAZW1haWwuY29tJywgJ0FkbWluMTIzJyk7Cg==
